### ISSUE TITLE
allow different configurations per deployment environment

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/dcp-fusillade#2]
The configuration will be different across the different deployments. We need a way to store the configuration for each deployment without affecting other deployments. 

## Definition of Done
- the configuration per stage is store separately from github, maybe s3
- Running `setup_fusillade.py {stage} --file {path}` will retrieve the config and deploy the changes.
- Store users and group association in a bucket
- Update dcp-fusillade infra with bucket creation

**Comment by amarjandu** [comment]
Addressed with data-store#2587
