### ISSUE TITLE
Add config files for populating users and groups in CI/CD tests to repo

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/dcp-fusillade#5]
Add fusillade config files to create users and groups to this repo.

These users and groups are common to all DCP components, and are created by each component as part of its DCP fusillade setup process. The users and groups common to the entire DCP are created first; roles specific to/defined by each component are created second.

This repo contains fusillade config files for defining users/groups common to all DCP components.

DCP component repos contain fusillade config files for defining roles specific to that component.

**Comment by Bento007** [comment]
Add documentation to the allspark wiki on how to modify the the dcp-fusillade config for each deployment stage.

**Comment by chmreid** [comment]
These are here: https://github.com/HumanCellAtlas/dcp-fusillade/tree/master/config
