### ISSUE TITLE
Add access keys for Allspark dcp-fusillade access to DCP secrets manager

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/dcp-fusillade#6]
The dcp-fusillade repository on Allspark (which is a mirror of this Github repo) is private. However, each component needs to be able to access this repo and the scripts/config files contained in it. To access this repo, we need to create an access token (which we did, see #4 and [these instructions in the dss-runbook](https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/GitLab%20Runbook#creating-a-mirrored-repository-private)) and store that access token in the DCP secrets manager (as described in [this comment](https://github.com/HumanCellAtlas/dcp-fusillade/issues/3#issuecomment-531009545) in issue #3). This will allow each component to use the secrets manager to access the token to clone the repo, which must be done before fusillade can be modified by each component.

**Comment by Bento007** [comment]
I believe this ticket is obsolete since we have made dcp-fusillade public and components and access the repo as needed.
